# Starter pipeline
trigger:
- formato1007

pool:
  name: 'TestePool'
  #vmImage: ubuntu-latest

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

steps:
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: SSH@0
  inputs:
    sshEndpoint: 'AgenteWindowsssh'
    runOptions: 'commands'
    commands: |
      echo variables
      more Downloads\\file.config
      echo ejecutar bat
      Downloads\\filebat.bat
      powershell Get-Content -path C:\Users\pocdevops\Downloads\file.config
      content = powershell (Get-Content -path C:\Users\pocdevops\Downloads\file.config -Raw) -replace 'brown','white'
      content | powershell Set-Content -Path C:\Users\pocdevops\Downloads\file.config
      powershell Get-Content -path C:\Users\pocdevops\Downloads\file.config
    readyTimeout: '20000'
