# Starter pipeline
trigger:
- pruebaPipelines

pool:
  name: 'TestePool'
  #vmImage: ubuntu-latest

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

steps:
- task: PowerShellOnTargetMachines@3
  inputs:
    Machines: 'pocdevops.eastus2.cloudapp.azure.com:5986'
    UserName: 'pocdevops'
    UserPassword: 'P@ssw0rd358*'
    InlineScript: |
      # Write your powershell commands here.
      
      Write-Output "Hello World"
    CommunicationProtocol: 'Http'
- task: PowerShellOnTargetMachines@3
  inputs:
    Machines: 'pocdevops.eastus2.cloudapp.azure.com:5986'
    UserName: 'pocdevops'
    UserPassword: 'P@ssw0rd358*'
    InlineScript: |
      # Write your powershell commands here.
      
      Write-Output "Hello World"
    CommunicationProtocol: 'Http'
- task: PowerShellOnTargetMachines@3
  inputs:
    Machines: '20.114.250.35;5986'
    UserName: 'pocdevops'
    UserPassword: 'P@ssw0rd358*'
    InlineScript: |
      # Write your powershell commands here.
      echo hola
      Write-Output "Hello World"
- template: templates/parameters.yml  # Template reference
  parameters:
    cambiar: false
    ruta: 'C:\Users\pocdevops\Downloads\file.config'
    buscar: 'white'
    reemplazarpor: 'nuevo'
- template: templates/parameters.yml  # Template reference
  parameters:
    reemplazarenxml: true
    ruta: 'C:\Users\pocdevops\Documents\PruebaPtos\file2.config'
    estructuraxml: 'configuration.appSettings.add.key'
    estructuraexterna: 'configuration.appSettings'
    item: 0
    reemplazarpor: '5050'
