# Starter pipeline
trigger:
- formato1007

pool:
  name: 'TestePool'
  #vmImage: ubuntu-latest

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

steps:
- script: |
  displayName: 'Run a multi-line script'

- task: SSH@0
  inputs:
    sshEndpoint: 'AgenteWindowsssh'
    runOptions: 'commands'
    commands: |
      more Downloads\\file.config
      echo ejecutar bat
      Downloads\\filebat.bat
      Get-Content -path C:\Users\pocdevops\Downloads\file.config
      (Get-Content -path C:\Users\pocdevops\Downloads\file.config -Raw) -replace 'brown','white'|  Set-Content -Path C:\Users\pocdevops\Downloads\file.config
      more Downloads\\file.config
    readyTimeout: '20000'
