# Starter pipeline
trigger: 
- pruebaPipelines
# new coment
#schedules:
#  - cron: '25 19 * * Mon-Fri'
#    displayName: M-F 10:40 daily build
#    branches:
#      include:
#      - pruebaPipelines
      
pool:
  name: 'TestePool'
  #vmImage: ubuntu-latest

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
stages:
  - stage: pssremoting3
    dependsOn: []
    jobs:
      - job: job1
        steps:
        - task: InstallSSHKey@0
          inputs:
            knownHostsEntry: 'devops Key'
            sshPublicKey: '$(myPubKey)'
            sshKeySecureFile: '$(myPubKey)'
        - task: SSH@0
          inputs:
            sshEndpoint: 'AgenteWindowsssh'
            runOptions: 'commands'
            commands: |
              echo "comandos git: " $(cd C:\Users\pocdevops\Documents\Eliminar\AZFunctionsPython) $(git branch) $(git pull)
              # git clone git@ssh.dev.azure.com:v3/itse8/HAXA/AZFunctionsPython
              git branch
              git pull
            readyTimeout: '20000'
        - template: templates/parameters.yml  # Template reference
          parameters:
            renombrarArchivo: 'true'
            rutaArchivoARenombrar: 'C:\Users\pocdevops\Downloads\file.config'
            nuevoNombreArchivo: 'fileRenamedXYZ.config'

            copiarCarpeta: 'true'
            hacerBackup: 'true'
            rutaCarpetaEnGit: 'filesToCopy'
            rutaCarpetaServidor: 'Documents\CopiesOfFiles'

            estructuraxml: 'configuration.appSettings.add'
            estructuraexterna: 'configuration.appSettings'
            item: 0
            reemplazarpor: '9999'

  - stage: pssremoting
    #dependsOn: []
    jobs:
      - job: job2
        steps:
          #- script: ''
          - task: SSH@0
            inputs:
              sshEndpoint: 'AgenteWindowsssh'
              runOptions: 'commands'
              commands: |
                iisreset
              readyTimeout: '20000'
        displayName: Reset IIS
  
  #- stage: pssremoting
    #dependsOn: []
    #jobs:
      #- job: job2
        #steps:
        #- task: PowerShellOnTargetMachines@3
          #inputs:
            #Machines: 'pocdevops.eastus2.cloudapp.azure.com'
            #UserName: pocdevops\pocdevops
            #UserPassword: P@ssw0rd358*
            #InlineScript: |
              # Write your powershell commands here.
              
              #Write-Output "Hello World"
            #CommunicationProtocol: 'Https'
  
