parameters:
  - name: cambiar
    type: boolean
    default: false
  - name: ruta
    type: string
    default: default
  - name: rutacompleta
    type: string
    default: default
  - name: reemplazarpor
    type: string
    default: ''


steps:
  - '${{ if eq(parameters.cambiar, true) }}':
    - script: ''
      displayName: reemplazar
    - task: SSH@0
      inputs:
        sshEndpoint: AgenteWindowsssh
        runOptions: commands
        commands: |
          more ${{parameters.ruta}} #Downloads\\file.config
          (Get-Content -path ${{parameters.rutacompleta}} -Raw) -replace 'white', '${{parameters.reemplazarpor}}'
          Set-Content -Path ${{parameters.rutacompleta}}
          more ${{parameters.ruta}}
        readyTimeout: '20000'
