parameters:
  - name: cambiar
    type: boolean
    default: false
  - name: ruta
    type: string
    default: default
  - name: rutaCompleta
    type: string
    default: default
  - name: reemplazarpor
    type: string
    default: ''


steps:
  - script: ''
  - '${{ if eq(parameters.cambiar, true) }}':
      - script: ''
        displayName: Run a multi-line script
      - task: SSH@0
        inputs:
          sshEndpoint: AgenteWindowsssh
          runOptions: commands
          commands: >
            more ${{parameters.ruta}} #Downloads\\file.config
            (Get-Content -path ${{parameters.rutaCompleta}} -Raw) -replace
            'white','negro'| Set-Content -Path ${{parameters.rutacompleta}}
            more ${{parameters.ruta}}
          readyTimeout: '20000'
