parameters:
  - name: renombrarArchivo
    type: boolean
    default: false
  - name: rutaArchivoARenombrar
    type: string
    default: ''
  - name: nuevoNombreArchivo
    type: string
    default: ''
    
  - name: copiarCarpeta
    type: boolean
    default: false
  - name: rutaCarpetaEnGit
    type: string
    default: ''
  - name: rutaCarpetaServidor
    type: string
    default: ''
  - name: hacerBackup
    type: boolean
    default: true
    
  - name: reemplazarenxml
    type: boolean
    default: false
  - name: estructuraxml
    type: string
    default: ''
  - name: estructuraexterna
    type: string
    default: ''
  - name: item
    type: number
    default: 0
  - name: noasignado
    type: string
    default: ''
  - name: ruta
    type: string
    default: ''
  - name: reemplazarpor
    type: string
    default: ''
  - name: buscar
    type: string
    default: ''

steps:
  - '${{ if eq(parameters.renombrarArchivo, true) }}':
    - script: ''
      displayName: Renombrar archivo
    - task: SSH@0
      inputs:
        sshEndpoint: 'AgenteWindowsssh'
        runOptions: 'commands'
        commands: |
          Rename-Item ${{parameters.rutaArchivoARenombrar}} ${{parameters.nuevoNombreArchivo}}
        readyTimeout: '20000'
  - '${{ if eq(parameters.copiarCarpeta, true) }}':
    - script: ''
      displayName: Copiar carpeta
    - '${{ if eq(parameters.hacerBackup, true) }}':
      - task: SSH@0
      inputs:
        sshEndpoint: 'AgenteWindowsssh'
        runOptions: 'commands'
        commands: |
          Copy-item -Force -Recurse -Verbose ${{parameters.rutaCarpetaServidor}} -Destination ${{parameters.rutaCarpetaServidor}}/Backup
        readyTimeout: '20000'
    - task: CopyFilesOverSSH@0
          inputs:
            sshEndpoint: 'AgenteWindowsssh'
            sourceFolder: '.\${{parameters.rutaCarpetaEnGit}}'
            contents: '**'
            targetFolder: '${{parameters.rutaCarpetaServidor}}'
            isWindowsOnTarget: true
            readyTimeout: '20000'
        
        
  - '${{ if eq(parameters.cambiar, true) }}':
    - script: ''
      displayName: Modo reemplazar ${{parameters.buscar}} por ${{parameters.reemplazarpor}} en ${{parameters.ruta}}
    - task: SSH@0
      inputs:
        sshEndpoint: AgenteWindowsssh
        runOptions: commands
        commands: |
          more ${{parameters.ruta}} 
          (Get-Content -path ${{parameters.ruta}} -Raw) -replace '${{parameters.buscar}}', '${{parameters.reemplazarpor}}'| Set-Content -Path ${{parameters.ruta}}
          more ${{parameters.ruta}}
        readyTimeout: '20000'
  - '${{ if eq(parameters.reemplazarenxml, true) }}':
    - script: ''
      displayName: Modo reemplazar en xml
    - task: SSH@0
      inputs:
        sshEndpoint: 'AgenteWindowsssh'
        runOptions: 'commands'
        commands: |
          echo ([xml]$myXML =  get-content ${{parameters.ruta}}) -and echo ($myXML.${{parameters.estructuraexterna}}.ChildNodes.Item(${{parameters.item}}).value="${{parameters.reemplazarpor}}") -and echo ($myXML.save('${{parameters.ruta}}'))
          echo ([xml]$myXML =  get-content ${{parameters.ruta}}) -and echo (($myXML).${{parameters.estructuraxml}})
        interpreterCommand: ''
        readyTimeout: '20000'

      
