parameters:
  - name: cambiar
    type: boolean
    default: false
  - name: ruta
    type: string
    default: ''
  - name: reemplazarpor
    type: string
    default: ''
  - name: buscar
    type: string
    default: ''
  - name: reemplazarenxml
    type: boolean
    default: false
  - name: estructuraxml
    type: string
    default: ''
  - name: estructuraexterna
    type: string
    default: ''
  - name: item
    type: number
    default: 0
  - name: noasignado
    type: string
    default: ''

steps:
  - '${{ if eq(parameters.cambiar, true) }}':
    - script: ''
      displayName: Modo reemplazar ${{parameters.buscar}} por ${{parameters.reemplazarpor}} en ${{parameters.ruta}}
    - task: SSH@0
      inputs:
        sshEndpoint: AgenteWindowsssh
        runOptions: commands
        commands: |
          more ${{parameters.ruta}} 
          (Get-Content -path ${{parameters.ruta}} -Raw) -replace '${{parameters.buscar}}', '${{parameters.reemplazarpor}}'| Set-Content -Path ${{parameters.ruta}}
          more ${{parameters.ruta}}
        readyTimeout: '20000'
  - '${{ if eq(parameters.reemplazarenxml, true) }}':
    - script: ''
      displayName: Modo reemplazar en xml
    - task: SSH@0
      inputs:
        sshEndpoint: AgenteWindowsssh
        runOptions: commands
        commands: |
          [xml]$myXML =  get-content ${{parameters.ruta}}; 
          $myXML.${{parameters.estructuraexterna}};
          $myXML.${{parameters.estructuraexterna}}.childNodes.Item(${{parameters.item}}).value = "${{parameters.reemplazarpor}}";
          $myXML.save('${{parameters.ruta}}');
          [xml]$myXML =  get-content ${{parameters.ruta}};
          $myXML.${{parameters.estructuraexterna}}
        readyTimeout: '20000'
      
