parameters:
  - name: reemplazar
    type: boolean
    default: false
  - name: ruta
    type: string
    default: ''
  - name: buscar
    type: string
    default: ''
  - name: reemplazarPor
    type: string
    default: ''


steps:
  - script: ''
  - '${{ if eq(parameters.reemplazar, true) }}':
      - script: ''
        displayName: Reemplazar mode
      - task: SSH@0
        inputs:
          sshEndpoint: AgenteWindowsssh
          runOptions: commands
          commands: >
            more ${{parameters.ruta}} 
            echo buscar ${{parameters.buscar}} y reemplazar por ${{parameters.reemplazarPor}}
            (Get-Content -path ${{parameters.ruta}} -Raw) -replace ${{parameters.buscar}},${{parameters.reemplazarPor}} | Set-Content -Path ${{parameters.ruta}}
            more ${{parameters.ruta}}
          readyTimeout: '20000'
